### ISSUE TITLE
NaN in timestamp column

### ISSUE THREAD

**Issue by bandtank** [alex/nyt-2020-election-scraper#266]
The timestamp column is showing NaN instead of a timestamp. The tooltip is working, though.

Windows 10
Edge (latest)
It wasn't like this when I last checked approximately 7 hours ago.

![image](https://user-images.githubusercontent.com/1170415/98395508-7336eb80-2000-11eb-9984-93495949bb55.png)

**Comment by thomasdesr** [comment]
Hey @bandtank !

We're having difficulty reproducing this on our end. Can you share:
* Any useful web console logs
* Does a hard refresh fix it?
* Are you running pre or post chromium edge?

**Comment by jordandukart** [comment]
Reproducible in an incognito window in FF 82.0.2.

Hard refresh doesn't fix, nothing in the console.

**Comment by thomasdesr** [comment]
Thanks! We have a theory, what timezones are your devices configured with? We think this might be related to the timestamp localization we merged.

**Comment by sigmaeni** [comment]
Same issue for me. Happens in Chrome version 86.0.4240.111

Some additional details on the problem:
Tooltip for all timestamps (including last scrape, last batch) shows a date, but not in the expected format. (example: 04 Nov 2020 9:40:57 AM AKST) Note the AKST instead of UTC. That's local time for me (perhaps queried from my computer?)

**Comment by PapaMurf** [comment]
Same issue for me as well. Interestingly AKST is my local time for me also.

**Comment by jordandukart** [comment]
AST here.

**Comment by s3bash** [comment]
Same problem for me. Chrome 86 and firefox on fedora linux, both show the same, timezone is HST. No console errors. Hard refresh does not fix the problem.

**Comment by bandtank** [comment]
This is in new Edge (old Edge needs to be nuked from orbit). I'm also seeing it in other browsers in both regular and incognito modes. Hard refreshes don't change the behavior, so I'm pretty sure it isn't a caching issue.

Tooltip timestamps are in HST for me (my local timezone). @s3bash I'm on Maui. How about you?

**Comment by thomasdesr** [comment]
Thanks for the timezones folks! That was the key :D

Working on the fix now X.X

**Comment by jordandukart** [comment]
Can confirm https://github.com/alex/nyt-2020-election-scraper/pull/273 fixed.

**Comment by s3bash** [comment]
Can confirm fixed in HST. @bandtank im on Oahu

**Comment by thomasdesr** [comment]
Glad to hear! Thanks for the reports everyone :D
